### ISSUE TITLE
May I add some more feature as show in the screencast?

### ISSUE THREAD

**Issue by alok-38** [MrSaeedNasiri/fresh-todo-list#3]
https://user-images.githubusercontent.com/121376211/215310246-83eae2ce-cb02-43c8-b437-2a4c6fe190b8.mp4

![Screenshot from 2023-01-29 12-24-17](https://user-images.githubusercontent.com/121376211/215310319-04a4b74a-5d0d-495e-8e29-a19686cec93b.png)

**Comment by alok-38** [comment]
https://user-images.githubusercontent.com/121376211/215310149-9ff29c5b-b0e4-48e4-8c7e-a018e16ae54d.mp4

**Comment by alok-38** [comment]
![Screenshot from 2023-01-29 12-24-17](https://user-images.githubusercontent.com/121376211/215310277-65abe6e4-30ee-4570-b731-2d74d91424d4.png)

**Comment by MrSaeedNasiri** [comment]
Dear @alok-38 
This is wonderful !
Of course, feel free to contribute.

**Comment by alok-38** [comment]
This is not yet complete. I have not started yet.
